### ISSUE TITLE
Add/update preview images

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/dark-reader#8]
## Description

This repository predates the updated template used in [catppuccin/template](https://github.com/catppuccin/template) so we should add preview images to the repository to be used in the README.

## Acceptance Criteria

1. The following images are added to the `assets` folder:
	- `latte.webp`
	- `frappe.webp`
	- `macchiato.webp`
	- `mocha.webp`
	- `preview.webp` generated by [catwalk](https://github.com/catppuccin/toolbox/tree/main/catwalk).
2. The `README.md` is updated to showcase the preview images.

**Comment by NeonGamerBot-QK** [comment]
Will add this soon!
